# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BLXUItRUrrJVlql1G9V1jaG_pStfeOKT
"""

try:
    # Step 1: Create a new text file and write three lines of text
    with open("my_file.txt", 'w') as file:
        file.write("Hello, my name is martin 1.\n")
        file.write("i am 28 years old.\n")
        file.write("i live in Nigeria.\n")

    # Step 2: Read the contents of the file and display them
    with open("my_file.txt", 'r') as file:
        print("Contents of 'my_file.txt' after initial write:")
        print(file.read())

    # Step 3: Open the file in append mode and add three more lines
    with open("my_file.txt", 'a') as file:
        file.write("I love coding\n")
        file.write("Adding this line 5 with a random number: 99.\n")
        file.write("Final line 6 to end the file content.\n")

    # Step 4: Read the updated contents of the file and display them
    with open("my_file.txt", 'r') as file:
        print("Contents of 'my_file.txt' after appending:")
        print(file.read())

except FileNotFoundError:
    print("Error: The file 'my_file.txt' was not found.")
except PermissionError:
    print("Error: You do not have permission to access 'my_file.txt'.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")
finally:
    print("File handling operations completed.")